import { Category, Company, Tool } from "./types";

export const CATEGORIES: Category[] = [
  { id: "c1", name: "Furadeiras", icon: "build" },
  { id: "c2", name: "Jardinagem", icon: "local-offer" },
  { id: "c3", name: "Construção", icon: "store" },
  { id: "c4", name: "Pintura", icon: "build" },
  { id: "c5", name: "Elétrica", icon: "build" },
  { id: "c6", name: "Limpeza", icon: "build" },
];

export const COMPANIES: Company[] = [
  {
    id: "co1",
    name: "FerraMax Locações",
    logo: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=200&q=80",
    description: "Especialista em ferramentas elétricas profissionais.",
    categoryId: "c1",
    rating: 4.8,
    ratingCount: 124,
    location: "São Paulo, SP",
  },
  {
    id: "co2",
    name: "JardimPro Aluguel",
    logo: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=200&q=80",
    description: "Equipamentos de jardinagem e paisagismo.",
    categoryId: "c2",
    rating: 4.6,
    ratingCount: 89,
    location: "Campinas, SP",
  },
  {
    id: "co3",
    name: "ConstruRent",
    logo: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=200&q=80",
    description: "Máquinas pesadas e equipamentos de construção.",
    categoryId: "c3",
    rating: 4.9,
    ratingCount: 210,
    location: "Guarulhos, SP",
  },
  {
    id: "co4",
    name: "PintaFácil Tools",
    logo: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=200&q=80",
    description: "Tudo para pintura residencial e comercial.",
    categoryId: "c4",
    rating: 4.4,
    ratingCount: 56,
    location: "Santo André, SP",
  },
];

export const TOOLS: Tool[] = [
  {
    id: "t1",
    companyId: "co1",
    name: "Furadeira de Impacto 750W",
    description: "Furadeira profissional com mandril de 13mm, ideal para concreto e alvenaria.",
    categoryId: "c1",
    image: "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=400&q=80",
    pricePerDay: 35,
    available: true,
  },
  {
    id: "t2",
    companyId: "co1",
    name: "Parafusadeira a Bateria 18V",
    description: "Parafusadeira sem fio com duas baterias e maleta.",
    categoryId: "c1",
    image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400&q=80",
    pricePerDay: 28,
    available: true,
  },
  {
    id: "t3",
    companyId: "co2",
    name: "Cortador de Grama Elétrico",
    description: "Cortador de grama 1400W com cesto coletor de 35L.",
    categoryId: "c2",
    image: "https://images.unsplash.com/photo-1599629954294-14df9ec8bcf8?w=400&q=80",
    pricePerDay: 45,
    available: true,
  },
  {
    id: "t4",
    companyId: "co2",
    name: "Roçadeira a Gasolina",
    description: "Roçadeira potente para áreas extensas e mato alto.",
    categoryId: "c2",
    image: "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?w=400&q=80",
    pricePerDay: 60,
    available: true,
  },
  {
    id: "t5",
    companyId: "co3",
    name: "Betoneira 120L",
    description: "Betoneira robusta para preparo de concreto e argamassa.",
    categoryId: "c3",
    image: "https://images.unsplash.com/photo-1517089152318-42ec560349c0?w=400&q=80",
    pricePerDay: 90,
    available: true,
  },
  {
    id: "t6",
    companyId: "co3",
    name: "Andaime Tubular 1,5m",
    description: "Módulo de andaime com plataforma, seguro e estável.",
    categoryId: "c3",
    image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=400&q=80",
    pricePerDay: 40,
    available: true,
  },
  {
    id: "t7",
    companyId: "co4",
    name: "Compressor de Ar 25L",
    description: "Compressor ideal para pintura com pistola e pequenos reparos.",
    categoryId: "c4",
    image: "https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=400&q=80",
    pricePerDay: 55,
    available: true,
  },
  {
    id: "t8",
    companyId: "co4",
    name: "Lixadeira Orbital",
    description: "Lixadeira para preparação de superfícies antes da pintura.",
    categoryId: "c4",
    image: "https://images.unsplash.com/photo-1607435097405-db48f377bff6?w=400&q=80",
    pricePerDay: 30,
    available: true,
  },
];
